<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><GenerateDocumentationFile>true</GenerateDocumentationFile><NoWarn>$(NoWarn);1591</NoWarn><PackageLicenseExpression>Apache-2.0</PackageLicenseExpression></PropertyGroup><ItemGroup><PackageReference Include="NodaTime" Version="3.2.2" /></ItemGroup></Project>
