<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><GenerateDocumentationFile>true</GenerateDocumentationFile><NoWarn>$(NoWarn);1591</NoWarn><PackageLicenseExpression>Apache-2.0</PackageLicenseExpression></PropertyGroup><ItemGroup><ProjectReference Include="../TravelRepo.Providers.Abstractions/TravelRepo.Providers.Abstractions.csproj" /><ProjectReference Include="../TravelRepo.Serialization/TravelRepo.Serialization.csproj" /></ItemGroup></Project>
